### ISSUE TITLE
No start file / Install Instructions

### ISSUE THREAD

**Issue by gubareve** [StudentVue-Community/SynergyServer#1]
Hello,

I am trying to get this up and working but when I run npm install I get this:

`npm [ERR!] missing script: start`

Could you help me out with the install process.

Thanks,
Evan

**Comment by kajchang** [comment]
Working on it

**Comment by WickedTree** [comment]
Try adding a start script in package.json.

**Comment by kajchang** [comment]
I updated the readme, but I'm not sure how clear it is as getting it to work nicely isn't that straightforward of a process. Tell me if you have any questions!

**Comment by gubareve** [comment]
Hi,

Sorry for the late reply.

I have fully set up the server, but when I try to connect by the student vue app, I get access code -100. As shown:
![image](https://user-images.githubusercontent.com/24500411/78103850-c24ddb80-73a2-11ea-8a28-fd03cfdb3acd.png)
These are my server logs:
`info Attempting to bind to /Service/PXPCommunication.asmx`

`info Trying PXPCommunicationSoap from path //Service/PXPCommunication.asmx`

`info Trying PXPCommunicationSoap12 from path //Service/PXPCommunication.asmx`

`replied <?xml version="1.0" encoding="utf-8"?><soap:Envelope 
xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"  xmlns:tns="http://edupoint.com/webservices/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"><soap:Body/></soap:Envelope>
`

Is there something i am doing wrong?

Thanks,
Evan

**Comment by kajchang** [comment]
Weird. What's the log right above that?

**Comment by gubareve** [comment]
Server is listening on port 3030
info Handling POST on /Service/PXPCommunication.asmx
received <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ProcessWebServiceRequest xmlns="http://edupoint.com/webservices/"><userID>string</userID><password>string</password><skipLoginLog>1</skipLoginLog><parent>0</parent><webServiceHandleName>PXPWebServices</webServiceHandleName><methodName>TestWebServiceURL</methodName><paramStr></paramStr></ProcessWebServiceRequest></soap:Body></soap:Envelope>

info Attempting to bind to /Service/PXPCommunication.asmx
info Trying PXPCommunicationSoap from path //Service/PXPCommunication.asmx
info Trying PXPCommunicationSoap12 from path //Service/PXPCommunication.asmx
replied <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"  xmlns:tns="http://edupoint.com/webservices/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"><soap:Body/></soap:Envelope>

**Comment by kajchang** [comment]
That's a really malformed looking request coming from the app, is that on Android or iOS?

**Comment by gubareve** [comment]
The app is iOS

**Comment by kajchang** [comment]
can you try connecting to `https://studentvue1.kaijchang.com`

**Comment by gubareve** [comment]
Connecting their works about half the time. The other half of the time your server responds with the same error.

**Comment by gubareve** [comment]
Mine is currently up at `ec2host.kd7t.com` would you mind trying to connect to it?

**Comment by gubareve** [comment]
info Handling GET on /Service/PXPCommunication.asmx
info Handling GET on /Service/PXPCommunication.asmx?WSDL
info Wants the WSDL
info Handling POST on /Service/PXPCommunication.asmx
received <?xml version="1.0" encoding="utf-8"?>
<soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Body><ProcessWebServiceRequest xmlns="http://edupoint.com/webservices/"><userID>string</userID><password>string</password><skipLoginLog>1</skipLoginLog><parent>0</parent><webServiceHandleName>PXPWebServices</webServiceHandleName><methodName>TestWebServiceURL</methodName><paramStr></paramStr></ProcessWebServiceRequest></soap:Body></soap:Envelope>

info Attempting to bind to /Service/PXPCommunication.asmx
info Trying PXPCommunicationSoap from path //Service/PXPCommunication.asmx
info Trying PXPCommunicationSoap12 from path //Service/PXPCommunication.asmx
replied <?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"  xmlns:tns="http://edupoint.com/webservices/" xmlns:tm="http://microsoft.com/wsdl/mime/textMatching/"><soap:Body/></soap:Envelope>

**Comment by kajchang** [comment]
Weird, I get the invalid URL thing for yours but I can't get it to happen for mine.

**Comment by gubareve** [comment]
Weird.

**Comment by gubareve** [comment]
Are your logs the same as mine?

**Comment by kajchang** [comment]
Can you try accessing mine again?

**Comment by gubareve** [comment]
Il try

**Comment by kajchang** [comment]
This probably isn't the problem, but I think your origin is set to `http://ec2host.kd7t.com/` when it should be set to `https://ec2host.kd7t.com`.

**Comment by gubareve** [comment]
I can't reach your's either right now. Il try removing the slash at the end.

**Comment by gubareve** [comment]
Yeah that doesnt help.

**Comment by kajchang** [comment]
There might be some weird networking thing going on because my server doesn't even log it when you try to access it.

**Comment by gubareve** [comment]
Are you on iOS?

**Comment by kajchang** [comment]
Did it work that time?

**Comment by gubareve** [comment]
I tried turning of wifi and turning on data and it forked for yours but mine didnt work. It weird because I dont have any firewall or anything.

**Comment by kajchang** [comment]
I still don't think this is the issue but your origin is still set wrong for me.

**Comment by gubareve** [comment]
Could you elaborate? I dont understand.

**Comment by kajchang** [comment]
Are you running it with `ORIGIN=https://ec2host.kd7t.com` as an environment variable?

**Comment by gubareve** [comment]
Ok I fixed that.

**Comment by gubareve** [comment]
And it works.

**Comment by gubareve** [comment]
Wow

**Comment by kajchang** [comment]
Nice! The wifi / cellular thing is still kind of weird though.

**Comment by gubareve** [comment]
It is weird. Mine works now and I cant connect to yours.

**Comment by kajchang** [comment]
Maybe it only allows one with the same organization name at the same time?

**Comment by gubareve** [comment]
Maybe. That would be weird. I will try.

**Comment by kajchang** [comment]
Going to go to sleep, tell me if you figure anything out. Thanks!

**Comment by gubareve** [comment]
Ok changed it. Im going to try now.

**Comment by gubareve** [comment]
I got a different error code. -1004

**Comment by gubareve** [comment]
In summary, this project is wonderful. Thanks for helping me set it up. I think I fixed the problem with connecting to your server by specifying port 443.

P.S. I cant get nohup to work. Help.

**Comment by kajchang** [comment]
Weird, I think that part of the reason might be that it sometimes still asks for the WSDL over http. I can check that.

**Comment by kaijchang** [comment]
I can connect to both now without any problems. Tell me if you're having any.

**Comment by ImpossibleReality** [comment]
@gubareve To use nohup, you would need to declare the environment variables before using nohup. E.X. `blah=blah nohup $command > logfile`
If that doesn't seem to work, try some other methods on https://unix.stackexchange.com/questions/308370/how-can-i-set-environment-variables-for-a-program-executed-using-nohup
